### ISSUE TITLE
nuxt的运行打开不了

### ISSUE THREAD

**Issue by lianghuiyong** [shi-lai-mu/wangEditor#1]
NuxtJs示例代码

我项目安装
    "@wangeditor/editor": "^0.12.7" 
或者 
    "@wangeditor/editor-for-vue": "^0.6.12-2",

npm安装或者yarm安装都报错了
截图上传不上去，发在v5体验群了

**Comment by GleamSlime** [comment]
已处理 （[链接](https://github.com/wangeditor-team/wangEditor-v5/issues/281)），待版本更新后请尝试安装0.12.7之后的版本，如有问题欢迎继续反馈，感谢

**Comment by lianghuiyong** [comment]
谢谢了！
